#!/usr/bin/bash
delete_one_row(){
    echo 'enter your column number :'
    read -r number_
    if  [[  ! $number_ =~ ^[0-9]+$ ]] ;
    then
    echo "error"
    else
    sed -i "$number_ d" $tname
    fi
}

delete_from_to(){
    echo 'enter your start number :'
    read -r num_start
    echo 'enter your end number :'
    read -r num_end
    if  [[ ! $num_start =~ ^[0-9]+$ ]] ;
    then
    echo "error"
    elif  [[ ! $num_end =~ ^[0-9]+$ ]] ;
    then
    echo "error"
    else
    sed -i "$num_start,$num_end d" $tname
    fi
}
delete_two_rows(){

echo 'enter your the first row:'
    read -r first
    echo 'enter the second row :'
    read -r second
    if  [[ ! $first=~ ^[0-9]+$ ]] ;
    then
    echo "error"
    elif  [[ ! $second =~ ^[0-9]+$ ]] ;
    then
    echo "error"
    else
    sed -i "$start,$second d" $tname
    fi

}



