#!/bin/bash
select_all_table () {
    

    ls -F |grep -v 'metadata' 
    echo -e "Enter the name of the table you want to select from : \c"
    read tname
  
    if [[ -f ${tname} ]]; then
        cat ${tname}
    else
        echo "Error displaying table $tname"
    fi
}


select_one_row () {
    ls -F |grep -v 'metadata' 
    echo -e "Enter the name of the table you want to select from : \c"
    read tname
  
    if [[ -f ${tname} ]]; then
    echo 'enter the id number :'
    read -r number_
    if  [[  ! $number_ =~ ^[0-9]+$ ]] ;
    then
    echo "error"
    else
    sed -n "$number p" $tname
    echo "the row $number has been selected:"
    fi
}

fun_select_from_table  () {
    echo "enter your option :"
       select option in select_all_table select_one_row 
       do 

       case $option in 
            
            1 ) 
             select_all_table ;; 

             2 ) 
             select_one_row   ;; 

             * ) 
             echo " invalid option :" ;; 

         esac


}