#!/usr/bin/bash
    select type in "string" "number"; do
        case $type in
            "string")
                echo "Selected type: string"
                break
                ;;
            "number")
                echo "Selected type: number"
                break
                ;;
            *)
                echo "Invalid selection. Please choose again."
                ;;
        esac
    done